Repository deluminators/Realate, pull requests merged in 2020-12, with the labels that each got.

#28 added swoc and dwoc to the readme section
  README.md
Labels: DWOC, Level-1, SWOC2021, documentation

#18 Responsive Navigation Bar Added.
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.css
  client/src/index.css
Labels: DWOC, Level-4, SWOC2021, code, feature

#31 Added dwoc and swoc to to readme and made them come inline
  README.html
  README.md
Labels: DWOC, Level-1, SWOC2021, documentation, good first issue
