Repository deluminators/Realate, pull requests merged in 2021-01, with the labels that each got.

#33 JWT Authentication Backend: Login and SignUp API, and User Model Added.
  app.js
  controllers/authenticationController.js
  models/createModel.js
  package-lock.json
  package.json
  routes/authenticationRoutes.js
  server.js
Labels: DWOC, Level-5, SWOC2021, code, feature

#39 Added SignIn and SignUp Components.
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignIn/fb.png
  client/src/components/Auth/SignIn/gog.png
  client/src/components/Auth/SignUp/SignUp.js
  client/src/components/Auth/SignUp/SignUp.module.css
  client/src/components/Header/Header.module.css
  client/src/index.css
  client/src/utils/validator.js
Labels: DWOC, Level-4, SWOC2021, UI, code, feature, hard

#37 Added Config file for Welcome BOT
  .github/config.yml
Labels: DWOC, Level-1, SWOC2021, documentation, easy

#40 README FILE WITH NICE BADGES
  README.md
Labels: DWOC, Level-1, SWOC2021, documentation, easy

#41 #38 Layout Component frontend
  client/src/App.css
  client/src/App.js
  client/src/assets/LayoutBG.jpg
  client/src/components/Layout/index.js
  client/src/components/Layout/layout.module.css
Labels: DWOC, Level-4, SWOC2021, UI, code, feature, medium

#46 Layout Fix/45
  client/src/App.js
  client/src/components/Layout/Layout.js
  client/src/components/Layout/Layout.module.css
Labels: DWOC, Level-3, SWOC2021, UI, bug, easy

#47 Home Section
  client/src/App.js
  client/src/assets/Logo.png
  client/src/components/Home/Home.js
  client/src/components/Home/Main/Main.js
  client/src/components/Home/Main/Main.module.css
  client/src/components/Home/Predictions/Predictions.js
  client/src/components/Home/Predictions/Predictions.module.css
Labels: DWOC, Level-4, SWOC2021, UI, code, feature, medium

#49 #43 React Reusable PredictionCard component
  client/src/components/Card/Card.module.css
  client/src/components/Card/PredictionCard.js
Labels: DWOC, Level-3, SWOC2021, UI, easy, feature
